In [1]:
import torch.nn as nn
import torch

In [129]:
class ICLabelNetImg(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.conv1 = nn.Conv2d(in_channels=1, 
                               out_channels = 128, 
                               kernel_size=4,
                               padding=1,
                               stride=2)
        self.relu1 = nn.LeakyReLU(negative_slope = 0.2)
        self.conv2 = nn.Conv2d(in_channels=128, 
                               out_channels = 256, 
                               kernel_size=4, 
                               padding=1,
                               stride=2)
        self.relu2 = nn.LeakyReLU(negative_slope = 0.2)
        self.conv3 = nn.Conv2d(in_channels=256, 
                               out_channels = 512, 
                               kernel_size=4,
                               padding=1,
                               stride=2)
        self.relu3 = nn.LeakyReLU(negative_slope = 0.2)
        self.sequential = nn.Sequential(self.conv1, self.relu1, 
                                        self.conv2, self.relu2, 
                                        self.conv3, self.relu3)
    
    def forward(self, x):
        return self.sequential(x)
    
class ICLabelNetPSDS(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.conv1 = nn.Conv2d(in_channels=1,
                               out_channels = 128,
                               kernel_size=(1,3),
                               padding=(0,1),
                               stride=1)
        self.relu1 = nn.LeakyReLU(negative_slope = 0.2)
        self.conv2 = nn.Conv2d(in_channels=128, 
                               out_channels = 256, 
                               kernel_size=(1,3), 
                               padding=(0,1),
                               stride=1)
        self.relu2 = nn.LeakyReLU(negative_slope = 0.2)
        self.conv3 = nn.Conv2d(in_channels=256, 
                               out_channels = 1, 
                               kernel_size=(1,3), 
                               padding=(0,1),
                               stride=1)
        self.relu3 = nn.LeakyReLU(negative_slope = 0.2)
        self.sequential = nn.Sequential(self.conv1, self.relu1, 
                                        self.conv2, self.relu2, 
                                        self.conv3, self.relu3)
    
    def forward(self, x):
        return self.sequential(x)
    
class ICLabelNetAutocorr(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.conv1 = nn.Conv2d(in_channels=1,
                               out_channels = 128,
                               kernel_size=(1,3),
                               padding=(0,1),
                               stride=1)
        self.relu1 = nn.LeakyReLU(negative_slope = 0.2)
        self.conv2 = nn.Conv2d(in_channels=128, 
                               out_channels = 256, 
                               kernel_size=(1,3), 
                               padding=(0,1),
                               stride=1)
        self.relu2 = nn.LeakyReLU(negative_slope = 0.2)
        self.conv3 = nn.Conv2d(in_channels=256,
                               out_channels = 1,
                               kernel_size=(1,3),
                               padding=(0,1),
                               stride=1)
        self.relu3 = nn.LeakyReLU(negative_slope = 0.2)
        self.sequential = nn.Sequential(self.conv1, self.relu1, 
                                        self.conv2, self.relu2, 
                                        self.conv3, self.relu3)
    
    def forward(self, x):
        return self.sequential(x)
    
class ICLabelNetConvProbs(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.conv = nn.Conv2d(in_channels  = 712,
                              out_channels = 7,
                              kernel_size  = (4,4),
                              padding      = 0,
                              stride       = 1)
        self.softmax = nn.Softmax(dim=1)
        
        self.seq = nn.Sequential(self.conv, self.softmax)
    
    def forward(self, x):
        return self.seq(x)

# Format input

In [3]:
import scipy.io as sio
import numpy as np

In [40]:
features = sio.loadmat('features.mat')['features']

images = features[0,0]
psds = features[0,1]
autocorrs = features[0,2]

In [43]:
formatted_images = np.concatenate((images, 
                                   -1 * images, 
                                   np.flip(images,axis=1), 
                                   np.flip(-1 * images,axis=1)), 
                                  axis=3)
formatted_psds = np.repeat(psds, 4, axis=3)
formatted_autocorrs = np.repeat(autocorrs, 4, axis=3)

In [135]:
img_tnsr = torch.permute(torch.from_numpy(formatted_images), (3, 2, 0, 1)).float()

psds_tnsr = torch.from_numpy(formatted_psds).float()
psds_tnsr = torch.permute(psds_tnsr, (3, 2, 0, 1)).float()

autocorrs_tnsr = torch.from_numpy(formatted_autocorrs).float()
autocorrs_tnsr = torch.permute(autocorrs_tnsr, (3, 2, 0, 1)).float()

## ICLabel Function

In [48]:
def reshape_fortran(x: torch.tensor, shape) -> torch.tensor:
    if len(x.shape) > 0:
        x = x.permute(*reversed(range(len(x.shape))))
    return x.reshape(*reversed(shape)).permute(*reversed(range(len(shape))))

In [149]:
def run_iclabel(images, psds, autocorr):
    img_net = ICLabelNetImg()

    # Load Params
    img_params = sio.loadmat('img_params.mat')
    permute = (3,2,0,1)
    img_weight1 = torch.permute(torch.from_numpy(img_params['conv1_kernel']), permute)
    img_weight2 = torch.permute(torch.from_numpy(img_params['conv2_kernel']), permute)
    img_weight3 = torch.permute(torch.from_numpy(img_params['conv3_kernel']), permute)
    img_bias1   = torch.squeeze(torch.from_numpy(img_params['conv1_bias']))
    img_bias2   = torch.squeeze(torch.from_numpy(img_params['conv2_bias']))
    img_bias3   = torch.squeeze(torch.from_numpy(img_params['conv3_bias']))

    img_net.state_dict()['conv1.weight'][:] = img_weight1
    img_net.state_dict()['conv1.bias'][:] = img_bias1
    img_net.state_dict()['conv2.weight'][:] = img_weight2
    img_net.state_dict()['conv2.bias'][:] = img_bias2
    img_net.state_dict()['conv3.weight'][:] = img_weight3
    img_net.state_dict()['conv3.bias'][:] = img_bias3
    
    # PSDS
    psds_net = ICLabelNetPSDS()

    # Load Params
    psds_params = sio.loadmat('psds_params.mat')

    psds_weight1 = torch.permute(torch.from_numpy(psds_params['conv1_kernel']), permute)
    psds_weight2 = torch.permute(torch.from_numpy(psds_params['conv2_kernel']), permute)
    psds_weight3 = torch.permute(torch.from_numpy(np.expand_dims(psds_params['conv3_kernel'], axis=2)), (2,3,0,1))
    psds_bias1   = torch.squeeze(torch.from_numpy(psds_params['conv1_bias']))
    psds_bias2   = torch.squeeze(torch.from_numpy(psds_params['conv2_bias']))
    psds_bias3   = torch.squeeze(torch.from_numpy(psds_params['conv3_bias']))

    psds_net.state_dict()['conv1.weight'][:] = psds_weight1
    psds_net.state_dict()['conv1.bias'][:]   = psds_bias1
    psds_net.state_dict()['conv2.weight'][:] = psds_weight2
    psds_net.state_dict()['conv2.bias'][:]   = psds_bias2
    psds_net.state_dict()['conv3.weight'][:] = psds_weight3
    psds_net.state_dict()['conv3.bias'][:]   = psds_bias3
    
    # Autocorr
    autocorr_net = ICLabelNetAutocorr()

    # Load Params
    autocorr_params = sio.loadmat('autocorrs_params.mat')

    autocorr_weight1 = torch.permute(torch.from_numpy(autocorr_params['conv1_kernel']), permute)
    autocorr_weight2 = torch.permute(torch.from_numpy(autocorr_params['conv2_kernel']), permute)
    autocorr_weight3 = torch.permute(torch.from_numpy(np.expand_dims(autocorr_params['conv3_kernel'], axis=2)), (2,3,0,1))
    autocorr_bias1   = torch.squeeze(torch.from_numpy(autocorr_params['conv1_bias']))
    autocorr_bias2   = torch.squeeze(torch.from_numpy(autocorr_params['conv2_bias']))
    autocorr_bias3   = torch.squeeze(torch.from_numpy(autocorr_params['conv3_bias']))

    autocorr_net.state_dict()['conv1.weight'][:] = autocorr_weight1
    autocorr_net.state_dict()['conv1.bias'][:]   = autocorr_bias1
    autocorr_net.state_dict()['conv2.weight'][:] = autocorr_weight2
    autocorr_net.state_dict()['conv2.bias'][:]   = autocorr_bias2
    autocorr_net.state_dict()['conv3.weight'][:] = autocorr_weight3
    autocorr_net.state_dict()['conv3.bias'][:]   = autocorr_bias3
    
    # Reshape and Concat
    out_img = img_net(images)
    out_psds = psds_net(psds)
    out_autocorr = autocorr_net(autocorr)

    # PSDS reshape, concat, permute
    psds_reshape = reshape_fortran(out_psds, [-1,1,1,100])
    psds_concat1 = torch.concat([psds_reshape, psds_reshape, psds_reshape, psds_reshape], 1)
    psds_concat2 = torch.concat([psds_concat1, psds_concat1, psds_concat1, psds_concat1], 2)
    psds_perm = torch.permute(psds_concat2, (0, 3, 1, 2))

    # Autocorr reshape, concat, permute
    autocorr_reshape = reshape_fortran(out_autocorr, [-1, 1, 1, 100])
    autocorr_concat1 = torch.concat([autocorr_reshape, autocorr_reshape, autocorr_reshape, autocorr_reshape], 1)
    autocorr_concat2 = torch.concat([autocorr_concat1, autocorr_concat1, autocorr_concat1, autocorr_concat1], 2)
    autocorr_perm = torch.permute(autocorr_concat2, (0, 3, 1, 2))

    concat = torch.concat([out_img, psds_perm, autocorr_perm], 1)
    
    # Final Conv and Softmax
    convNet = ICLabelNetConvProbs()

    # Load Params
    conv_params = sio.loadmat('conv_params.mat')

    conv_weight1 = torch.permute(torch.from_numpy(conv_params['conv_kernel']), permute)
    conv_bias1   = torch.squeeze(torch.from_numpy(conv_params['conv_bias']))

    convNet.state_dict()['conv.weight'][:] = conv_weight1
    convNet.state_dict()['conv.bias'][:]   = conv_bias1
    
    labels = convNet(concat)
    labels = labels.squeeze()
    labels = reshape_fortran(labels.permute(1,0), [-1, 4])
    labels = torch.mean(labels, 1)
    labels = reshape_fortran(labels, [7, -1])
    labels = labels.permute(1,0)
    
    return labels.detach().numpy()

In [150]:
labels_npy = run_iclabel(img_tnsr, psds_tnsr, autocorrs_tnsr)

In [138]:
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

In [142]:
labels_npy

array([[0.8979, 0.0001, 0.0002, 0.0002, 0.0973, 0.0005, 0.0037],
       [0.2666, 0.0006, 0.6091, 0.0025, 0.0679, 0.0033, 0.05  ],
       [0.4624, 0.0003, 0.0005, 0.0009, 0.4914, 0.0064, 0.0381],
       [0.756 , 0.0003, 0.0003, 0.0008, 0.1112, 0.0007, 0.1307],
       [0.9765, 0.0002, 0.0011, 0.0002, 0.0152, 0.0009, 0.0059],
       [0.2402, 0.0011, 0.4898, 0.0064, 0.1726, 0.0045, 0.0853],
       [0.704 , 0.0004, 0.1368, 0.0058, 0.1156, 0.0021, 0.0354],
       [0.8704, 0.0008, 0.0013, 0.0007, 0.0871, 0.0007, 0.039 ],
       [0.6157, 0.0002, 0.0004, 0.0005, 0.3623, 0.0011, 0.0198],
       [0.8579, 0.0011, 0.0004, 0.0012, 0.106 , 0.0014, 0.0319],
       [0.2302, 0.002 , 0.004 , 0.0008, 0.6885, 0.0337, 0.0407],
       [0.8634, 0.0006, 0.0003, 0.0003, 0.0786, 0.0013, 0.0554],
       [0.2203, 0.0006, 0.0219, 0.0039, 0.2163, 0.0171, 0.5198],
       [0.5618, 0.0002, 0.001 , 0.0009, 0.1016, 0.0003, 0.3342],
       [0.9025, 0.0003, 0.0034, 0.0023, 0.0338, 0.0013, 0.0565],
       [0.1397, 0.0001, 0

In [143]:
labels_mat = sio.loadmat('labels.mat')['labels']
labels_mat

array([[0.9883, 0.    , 0.    , 0.    , 0.0117, 0.    , 0.    ],
       [0.0066, 0.0005, 0.9627, 0.0009, 0.0042, 0.0028, 0.0224],
       [0.1333, 0.0004, 0.0009, 0.0021, 0.7133, 0.016 , 0.1339],
       [0.8638, 0.    , 0.0002, 0.0007, 0.1096, 0.0001, 0.0256],
       [0.9924, 0.    , 0.    , 0.    , 0.0073, 0.    , 0.0002],
       [0.0061, 0.0007, 0.7202, 0.0013, 0.2251, 0.0043, 0.0423],
       [0.7828, 0.    , 0.0044, 0.002 , 0.2021, 0.0008, 0.0078],
       [0.8543, 0.    , 0.    , 0.    , 0.1453, 0.    , 0.0004],
       [0.9153, 0.    , 0.    , 0.    , 0.084 , 0.    , 0.0006],
       [0.9927, 0.    , 0.    , 0.0001, 0.0071, 0.    , 0.0001],
       [0.6861, 0.0016, 0.0017, 0.0006, 0.2643, 0.0097, 0.0359],
       [0.9949, 0.    , 0.    , 0.    , 0.0038, 0.    , 0.0012],
       [0.0611, 0.0002, 0.0072, 0.0024, 0.6473, 0.0106, 0.2712],
       [0.5056, 0.0001, 0.0003, 0.0004, 0.4238, 0.    , 0.0698],
       [0.3032, 0.    , 0.0011, 0.0005, 0.6825, 0.0006, 0.012 ],
       [0.0548, 0.0001, 0

In [124]:
np.max(np.abs(labels_mat - labels_npy))

0.64871955

In [127]:
np.argmax(labels_npy, axis=1)

array([0, 2, 4, 0, 0, 2, 0, 0, 0, 0, 4, 0, 6, 0, 0, 6, 4, 4, 4, 0, 4, 4,
       0, 0, 6, 0, 6, 4, 0, 0, 4, 0])

In [128]:
np.argmax(labels_mat, axis=1)

array([0, 2, 4, 0, 0, 2, 0, 0, 0, 0, 0, 0, 4, 0, 4, 6, 4, 0, 4, 0, 4, 0,
       0, 0, 6, 0, 6, 6, 4, 0, 4, 6])